#! /bin/env python3
import sys

from pifcore.utils import prettyPrint
from pifcore.parser import Parser
from pifcore.transpiler import Transpiler

file = sys.argv[1]

ast = Parser().parse(file)

if len(sys.argv) > 2 and str(sys.argv[2]) == "--ast":
    prettyPrint(ast)
    exit()

Transpiler().transpile(file, ast)